spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.demo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

demo:
  jwt:
    user-secret-key: pepedd
    user-ttl: 6000000 # 60*1000
    user-token-name: authentication
server:
  port: 8081
